development:
  clients:
    default:
      database: Mappium_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: Mappium_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1
#
# production:
#   clients:
#     default:
#       database: Mappium_production
#       hosts:
#         - localhost:27017
#       options:
#   options:
#

production:
  clients:
    default:
     # The standard MongoDB connection URI allows for easy
     # replica set connection setup.
     # Use environment variables or a config file to keep your
     # credentials safe e.g. <%= ENV['MONGODB_URI'] %>.
     uri: "mongodb://heroku_75fsrczb:6hm04lng0sa4447d1u1gsgtv4d@ds019470.mlab.com:19470/heroku_75fsrczb"

     options:
       # The default timeout is 5, which is the time in seconds
       # for a connection to time out.
       # We recommend 15 because it allows for plenty of time
       # in most operating environments.
       connect_timeout: 15
